owner: ics-tools
repo: upptime

sites:
  - name: Hauptseite
    url: https://ics.tools
  - name: ics Viewer
    url: https://viewer.ics.tools

status-website:
  cname: status.ics.tools
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** überprüft die Verfügbarkeit der Webseite."
  introMessage: Uptime überprüft in regelmäßigen Abständen die Verfügbarkeit der unterschiedlichen Webseiten und ics-Dateien.
  navbar:
    - title: Status
      href: /
    - title: ics.tools
      href: https://ics.tools
    - title: GitHub - Status
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
